import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

const root = new URL('../', import.meta.url)
const html = readFileSync(new URL('public/admin-toilets-preview/index.html', root), 'utf8')
const script = readFileSync(new URL('public/admin-toilets-preview/toilets.js', root), 'utf8')
const styles = readFileSync(new URL('public/admin-toilets-preview/toilets.css', root), 'utf8')
const shell = readFileSync(new URL('public/admin-toilets-preview/admin-shell.js', root), 'utf8')
const route = readFileSync(new URL('src/app/admin-toilets-preview/map-config/route.ts', root), 'utf8')

test('admin toilet preview is isolated under the fixed preview route', () => {
  assert.match(html, /\/admin-toilets-preview\/toilets\.js/)
  assert.match(html, /id="toilet-search"/)
  assert.match(html, /id="toilet-sido"/)
  assert.match(html, /id="toilet-map-card"/)
  assert.match(html, /quality-review-shell\.css/)
  assert.match(html, /toilet-list-pane[\s\S]*toilet-map-card[\s\S]*toilet-editor-card/)
  assert.match(styles, /grid-template-columns:\s*minmax\(320px,.68fr\)\s*minmax\(460px,1.18fr\)\s*minmax\(450px,1.14fr\)/)
  assert.ok(shell.indexOf("nav('reports'") < shell.indexOf("nav('toilets'"))
  assert.match(script, /https:\/\/api\.geupddong\.com/)
  assert.match(script, /\/admin-toilets-preview\/map-config/)
  assert.match(script, /SUGGESTION_DELAY_MS = 60/)
  assert.match(script, /suggestionCache/)
  assert.match(script, /input\.addEventListener\('input', event => schedule\(\{ includeList: !event\.isComposing && !composing \}\)\)/)
  assert.doesNotMatch(script, /if \(composing\) return/)
  assert.match(script, /\/api\/v1\/toilets\?\$\{query\}/)
  assert.match(script, /toilet-public-marker/)
  assert.match(script, /toilet-marker-logo\.svg/)
  assert.match(script, /label\.textContent = name/)
  assert.match(script, /selectToilet\(Number\(toilet\.id\)\)/)
  assert.match(script, /const PAGE_SIZE = 10/)
  assert.match(styles, /\.toilet-list-address\s*\{[^}]*-webkit-line-clamp:\s*2/)
  assert.match(script, /width="24" height="38" viewBox="0 0 24 38"/)
  assert.match(script, /M12 11V36/)
  assert.match(script, /markerImage\(K,'#157d48'\)/)
  assert.match(script, /markerImage\(K,'#ee872c'\)/)
  assert.doesNotMatch(script, /if \(validCoordinates\(original\)\) editMarker\.setMap\(map\)/)
  assert.match(script, /const setCoordinate =[\s\S]*editMarker\.setMap\(map\)/)
})

test('preview uses existing real-data reads and blocks production writes', () => {
  assert.match(script, /api\/admin\/v1\/regions\?/)
  assert.match(script, /프리뷰 저장 차단/)
  assert.match(script, /const PREVIEW_READ_ONLY = true/)
  assert.match(script, /if \(PREVIEW_READ_ONLY \|\| legacyPreview\) return/)
  assert.match(route, /NEXT_PUBLIC_KAKAO_JAVASCRIPT_KEY/)
  assert.match(route, /private, no-store/)
})
