// Synthetic owner, reports, clock and GPS; no business writes leave this browser.
const assert = require('node:assert/strict')
const { selectCalendarDate } = require('./history-calendar-browser.cjs')
const fs = require('node:fs'), path = require('node:path')
const { chromium } = require(process.env.PLAYWRIGHT_PACKAGE || 'playwright')
const origin = process.env.REVIEW_PREVIEW_ORIGIN || 'http://127.0.0.1:4187'
assert.ok(['http://127.0.0.1:4187','https://preview.geupddong.com'].includes(origin))
const output = process.env.REVIEW_SCREENSHOT_DIR || path.resolve('.tmp-history-screenshots')
fs.mkdirSync(output,{recursive:true})
const now = Date.parse('2026-09-11T12:00:00+09:00'), day = 86400000
const mobileUserAgent = 'Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 Mobile/15E148 Safari/604.1'
const iso = age => new Date(now-age*day).toISOString()
;(async()=>{
 const browser=await chromium.launch({channel:'chrome',headless:true})
 try {
  for(const width of [390,320]) {
   const context=await browser.newContext({viewport:{width,height:844},isMobile:true,hasTouch:true,serviceWorkers:'block',userAgent:mobileUserAgent})
   let owner='history-owner', nextOwner='history-owner', reportMode='', reads=0, writes=0
   const reports=Array.from({length:25},(_,i)=>({id:i+1,toiletId:13144,toiletName:`목록 시험 ${String(i+1).padStart(2,'0')}`,reportType:'COORDINATE_CORRECTION',reason:'합성 제보 내용',roadAddress:'공개 시험 주소',status:i%2?'APPROVED':'PENDING',createdAt:new Date(now-i*1000).toISOString()}))
   reports.push({ ...reports[0],id:40,toiletName:'10일 전 시험',createdAt:iso(10) },{...reports[0],id:41,toiletName:'40일 전 시험',createdAt:iso(40)})
   await context.route('**/*',async route=>{
    const req=route.request(),u=new URL(req.url())
    if(u.pathname==='/api/v1/auth/me')return route.fulfill({json:owner?{userId:owner,displayName:'시험 사용자',status:'ACTIVE',roles:['USER'],consentRequired:false}:null})
    if(u.pathname.startsWith('/api/v1/auth/login/')) {owner=nextOwner;reportMode='';return route.fulfill({contentType:'text/html',body:`<script>location.replace('${origin}/?login=success#review-test=36.3504,127.3845')</script>`})}
    if(u.pathname==='/api/v1/auth/refresh')return route.fulfill({status:401,json:{}})
    if(u.pathname==='/api/v1/notifications/unread-count')return route.fulfill({json:{count:0}})
    if(u.pathname==='/api/v1/notifications')return route.fulfill({json:{items:[{id:1,type:'REPORT_APPROVED',referenceType:'TOILET_REPORT',referenceId:41,title:'오래된 제보 확인',message:'읽음 상태의 합성 알림',read:true,createdAt:iso(0)},{id:2,type:'REPORT_APPROVED',referenceType:'TOILET_REPORT',referenceId:15,title:'중간 제보 확인',message:'상단 위치 검사용 합성 알림',read:true,createdAt:iso(0)}],page:0,size:20,totalElements:2,totalPages:1}})
    if(u.pathname==='/api/v1/reports/me') {
     reads++
     if(reportMode==='offline')return route.abort('internetdisconnected')
     if(reportMode==='401'){owner=null;return route.fulfill({status:401,json:{}})}
     return route.fulfill({json:owner==='history-owner'?[...reports].reverse():[]})
    }
    if(u.pathname==='/api/v1/toilets')return route.fulfill({json:{meta:{map_level:4,display_type:'MARKER',total_count:0,result_count:0},toilets:[],clusters:[]}})
    if(u.pathname==='/cdn-cgi/rum')return route.fulfill({status:204})
    if(!['GET','HEAD','OPTIONS'].includes(req.method())){writes++;return route.abort()}
    if(origin.includes('127.0.0.1')&&u.hostname==='dapi.kakao.com')return route.abort()
    return route.continue()
   })
   await context.addInitScript(fixed=>{
    const RealDate=Date;window.historyTestNow=fixed
    window.Date=class extends RealDate { constructor(...args){if(args.length)super(...args);else super(window.historyTestNow)} static now(){return window.historyTestNow} }
    Object.defineProperty(navigator,'geolocation',{value:{getCurrentPosition(ok){setTimeout(()=>ok({coords:{latitude:36.3504,longitude:127.3845,accuracy:10},timestamp:Date.now()}),10)},watchPosition(){return 1},clearWatch(){}}})
   },now)
   if(origin.includes('127.0.0.1'))await context.addInitScript(()=>{
    document.addEventListener('DOMContentLoaded',()=>{
     const style=document.createElement('style');style.textContent='nextjs-portal {display:none!important}';document.head.append(style)
    })
    class LatLng {constructor(lat,lng){this.lat=lat;this.lng=lng}getLat(){return this.lat}getLng(){return this.lng}}
    class MapMock {constructor(el,options){this.el=el;this.center=options.center;this.level=options.level;this.listeners={}}getCenter(){return this.center}getLevel(){return this.level}getBounds(){return {getSouthWest:()=>new LatLng(36.34,127.37),getNorthEast:()=>new LatLng(36.36,127.39)}}getProjection(){return {pointFromCoords:()=>({x:180,y:300})}}relayout(){}panTo(p){this.center=p}setCenter(p){this.center=p}setDraggable(){}setZoomable(){}setLevel(v){this.level=v}}
    class Overlay {constructor(options){this.options=options}setMap(map){this.options.content.remove();if(map){Object.assign(this.options.content.style,{position:'absolute',left:'130px',top:'160px'});map.el.append(this.options.content)}}}
    window.kakao={maps:{Map:MapMock,LatLng,CustomOverlay:Overlay,event:{preventMap(){},addListener(map,name,fn){(map.listeners[name]??=[]).push(fn)}},services:{Status:{OK:'OK',ZERO_RESULT:'ZERO'}}}}
   })
   const page=await context.newPage(),errors=[]
   page.on('pageerror',e=>errors.push(e.message))
   await page.goto(origin+'/#review-test=36.3504,127.3845',{waitUntil:'networkidle'})
   await page.locator('.review-test-marker').waitFor()
   const nav=page.getByRole('navigation',{name:'하단 내비게이션'}), shell=page.locator('.mobile-page')
   const original=page.url(), header=await page.locator('.topbar').elementHandle(), navElement=await nav.elementHandle(), map=await page.locator('.map').elementHandle()
   const stable=async()=>{
    assert.equal(page.url(),original)
    for(const el of [header,navElement,map])assert.equal(await el.evaluate(el=>el.isConnected),true,'shell/map should not remount')
    const bounds=await shell.boundingBox(),bottom=await nav.boundingBox()
    assert.equal(await page.locator('.topbar').isVisible(),false,'account, report/review details and notification pages hide the map header')
    assert.equal(bounds.y,0,'history reclaims the old header space')
    assert.ok(bounds.y+bounds.height<=bottom.y+1,'history stays above bottom navigation')
    assert.equal(await shell.evaluate(el=>el.scrollWidth>el.clientWidth),false,'no horizontal overflow')
   }
   const showReports=async()=>{await nav.getByRole('button',{name:'내 페이지',exact:true}).click();assert.equal(await page.locator('.topbar').isVisible(),false,'account home also hides the map header');const homeTitle=await shell.locator('.mobile-page-heading h1').boundingBox();await shell.getByRole('button',{name:'내 제보',exact:true}).click();if(reportMode!=='401'){await shell.locator('.history-heading h1').waitFor();const reportTitle=await shell.locator('.history-heading h1').boundingBox();assert.ok(Math.abs(homeTitle.y-reportTitle.y)<1&&homeTitle.x===reportTitle.x,'report title matches account home position')}}
   const backToTop=async()=>{
    if(await shell.evaluate(el=>el.scrollTop)>=400)await shell.getByRole('button',{name:'맨 위로 이동'}).click()
    else await shell.evaluate(el=>el.scrollTo({top:0,behavior:'instant'}))
    await page.waitForFunction(()=>document.querySelector('.mobile-page').scrollTop===0)
   }
   await showReports();await shell.locator('.my-report-item').first().waitFor()
   assert.equal(await shell.evaluate(el=>el.scrollTop),0,'new report history starts at the top')
   assert.equal(await page.getByRole('dialog').count(),0)
   assert.equal(await shell.locator('.my-report-item').count(),10)
   assert.equal(await shell.locator('.history-filter-disclosure').count(),0,'no separate filter disclosure row')
   assert.equal(await shell.getByRole('button',{name:'최근 7일',exact:true}).getAttribute('aria-pressed'),'true')
   assert.equal(await shell.locator('.history-scroll-top').getAttribute('aria-hidden'),'true','TOP starts hidden')
   const periodButtons=await shell.locator('.history-periods button').evaluateAll(buttons=>buttons.map(button=>button.getBoundingClientRect().height))
   assert.ok(periodButtons.every(height=>height===40),'period and date toggle controls share a compact 40px height')
   assert.equal((await shell.getByRole('button',{name:'내 제보 닫기'}).boundingBox()).height,40)
   assert.equal((await shell.getByRole('navigation',{name:'제보 상태 필터'}).getByRole('button').first().boundingBox()).height,36)
   assert.match(await shell.locator('.my-report-item').first().innerText(),/목록 시험 01/)
   await stable();await page.screenshot({path:path.join(output,`reports-history-${width}.png`)})
   const layout=()=>shell.evaluate(el=>({top:el.scrollTop,height:el.scrollHeight,cardY:el.querySelector('.my-report-item').getBoundingClientRect().top}))
   const initialFilter=await shell.locator('.history-filter-shell').boundingBox()
   assert.equal(await shell.locator('.history-filter-shell').evaluate(el=>getComputedStyle(el).position),'static','filters are scroll content, not screen-sticky')
   await shell.evaluate(el=>{el.scrollTop=40});await page.waitForTimeout(50)
   assert.ok(Math.abs((await shell.locator('.history-filter-shell').boundingBox()).y-initialFilter.y+40)<=1,'filters move with the list')
   await shell.evaluate(el=>{el.scrollTop=399});await page.waitForTimeout(50)
   assert.equal(await shell.locator('.history-scroll-top').getAttribute('aria-hidden'),'true','TOP stays hidden before threshold')
   await shell.evaluate(el=>{el.scrollTop=400});await page.waitForFunction(()=>document.querySelector('.history-scroll-top').getAttribute('aria-hidden')==='false')
   const initialReads=reads
   await shell.evaluate(el=>{el.scrollTop=el.scrollHeight});await page.waitForFunction(()=>document.querySelectorAll('.mobile-page .my-report-item').length===20)
   await shell.evaluate(el=>{el.scrollTop=el.scrollHeight});await page.waitForFunction(()=>document.querySelectorAll('.mobile-page .my-report-item').length===25)
   assert.equal(reads,initialReads,'client append must not refetch the whole report array')
   const pinnedHeading=await shell.locator('.history-heading').boundingBox(), shellBounds=await shell.boundingBox()
   assert.ok(Math.abs(pinnedHeading.y-shellBounds.y)<=1,'history title and close stay pinned while scrolling')
   assert.equal(await shell.getByRole('button',{name:'내 제보 닫기'}).isVisible(),true)
   const scrolledFilter=await shell.locator('.history-filter-shell').boundingBox()
   assert.ok(scrolledFilter.y+scrolledFilter.height<shellBounds.y,'filters scroll completely out of view')
   await page.waitForTimeout(180)
   const topButton=shell.getByRole('button',{name:'맨 위로 이동'}), topBounds=await topButton.boundingBox(), navBoundsBefore=await nav.boundingBox()
   assert.ok(topBounds.y+topBounds.height<=navBoundsBefore.y-10,'TOP clears bottom navigation')
   assert.ok(Math.abs(topBounds.x+topBounds.width-shellBounds.x-shellBounds.width+16)<=1,'TOP aligns to the right of the scroll viewport')
   await page.screenshot({path:path.join(output,`reports-top-visible-${width}.png`)})
   await backToTop()
   assert.equal(await shell.locator('.my-report-item').count(),25,'TOP preserves the loaded list')
   assert.equal(reads,initialReads,'TOP does not refetch')
   assert.equal(await shell.locator('.history-heading h1').evaluate(el=>el===document.activeElement),true,'TOP returns keyboard focus to the heading')
   assert.equal(await shell.locator('.history-scroll-top').getAttribute('aria-hidden'),'true')
   await page.emulateMedia({reducedMotion:'reduce'})
   await shell.evaluate(el=>{el.scrollTop=450});await topButton.waitFor()
   assert.equal(await topButton.evaluate(el=>getComputedStyle(el).transitionDuration),'0s')
   await topButton.focus();await page.keyboard.press('Enter')
   assert.equal(await shell.evaluate(el=>el.scrollTop),0,'reduced-motion TOP returns immediately')
   await page.emulateMedia({reducedMotion:'no-preference'})
   await shell.getByRole('button',{name:'최근 30일',exact:true}).click()
   assert.match(await shell.locator('.history-range-caption').innerText(),/26개/)
   assert.equal(await shell.locator('.my-report-item').count(),10)
   await backToTop()
   await shell.getByRole('group',{name:'조회 기간'}).getByRole('button',{name:'전체',exact:true}).click()
   assert.match(await shell.locator('.history-range-caption').innerText(),/27개/)
   const beforeCalendar=await layout()
   await shell.getByRole('button',{name:'날짜 직접 선택'}).click()
   assert.equal(await shell.getByRole('button',{name:'취소',exact:true}).count(),0,'date picker has no redundant cancel action')
   assert.deepEqual(await layout(),beforeCalendar,'calendar expansion never changes the underlying list scroll range')
   const startBox=await shell.getByLabel('시작일',{exact:true}).boundingBox(), endBox=await shell.getByLabel('종료일',{exact:true}).boundingBox(), applyBox=await shell.getByRole('button',{name:'적용',exact:true}).boundingBox()
   assert.ok(Math.abs(startBox.y-endBox.y)<=1 && Math.abs(startBox.y-applyBox.y)<=1,'date inputs and apply action stay on one row')
   assert.equal(applyBox.width,64,'apply has enough horizontal space for its label')
   assert.ok([startBox,endBox,applyBox].every(box=>box.height===48),'date row has a consistent compact height')
   assert.ok(Math.abs(startBox.width-endBox.width)<=1,'start and end dates share the remaining width equally')
   assert.ok(Math.abs((endBox.x-startBox.x-startBox.width)-(applyBox.x-endBox.x-endBox.width))<=1,'date row gaps are balanced')
   assert.equal(await shell.locator('.history-date-field strong').evaluateAll(labels=>labels.some(label=>label.scrollWidth>label.clientWidth)),false,'date text is not clipped on narrow screens')
   assert.equal(await shell.locator('input[type=date]').count(),0,'custom calendar replaces device-native date popups')
   assert.equal(await shell.getByRole('button',{name:'2026년 9월 12일',exact:true}).isDisabled(),true,'future days cannot be selected')
   await selectCalendarDate(shell,'시작일','2026-08-02');await selectCalendarDate(shell,'종료일','2026-08-02')
   const focusedDay=shell.getByRole('button',{name:'2026년 8월 2일',exact:true})
   await focusedDay.focus();await page.keyboard.press('ArrowRight')
   // Calendar focus is applied on the next animation frame, not synchronously with keydown.
   await page.waitForFunction(()=>document.activeElement?.getAttribute('data-day')==='2026-08-03')
   assert.equal(await shell.getByRole('button',{name:'2026년 8월 3일',exact:true}).evaluate(el=>el===document.activeElement),true)
   assert.notEqual(await shell.getByRole('button',{name:'2026년 8월 3일',exact:true}).evaluate(el=>getComputedStyle(el).outlineStyle),'none','keyboard focus remains visible')
   const touchButton=shell.getByRole('button',{name:'날짜 직접 선택'})
   assert.equal(await touchButton.evaluate(el=>getComputedStyle(el).webkitTapHighlightColor),'rgba(0, 0, 0, 0)','no browser-native gray touch rectangle')
   await page.screenshot({path:path.join(output,`history-date-picker-${width}.png`)})
   await shell.getByRole('button',{name:'적용',exact:true}).click()
   assert.equal(await shell.locator('.my-report-item').count(),1)
   await shell.getByRole('button',{name:/40일 전 시험/}).click();await shell.getByText('합성 제보 내용',{exact:true}).waitFor();await stable()
   await backToTop()
   await shell.getByRole('button',{name:'날짜 직접 선택'}).click();await selectCalendarDate(shell,'시작일','2026-09-10');await selectCalendarDate(shell,'종료일','2026-09-01');await shell.getByRole('button',{name:'적용',exact:true}).click();await shell.getByRole('alert').filter({hasText:'종료일'}).waitFor();assert.equal(await shell.locator('.my-report-item').count(),1);await page.keyboard.press('Escape');assert.equal(await shell.locator('.history-calendar').count(),0);assert.equal(await shell.getByRole('button',{name:'날짜 직접 선택'}).evaluate(el=>el===document.activeElement),true)
   await shell.getByRole('button',{name:'최근 7일',exact:true}).click();await shell.getByRole('navigation',{name:'제보 상태 필터'}).getByRole('button',{name:/승인/}).click();assert.match(await shell.locator('.history-range-caption').innerText(),/12개/)
   await shell.getByRole('button',{name:'내 제보 닫기'}).click();await shell.getByRole('heading',{name:'내 페이지',exact:true}).waitFor()
   // Notification targets outside the default date/window still open in this shell.
   await nav.getByRole('button',{name:/^알림/}).click()
   await shell.getByRole('region',{name:'받은 알림 목록',exact:true}).getByRole('button',{name:/오래된 제보 확인/}).click()
   await shell.getByText('합성 제보 내용',{exact:true}).waitFor()
   await page.waitForFunction(()=>{const card=document.querySelector('.my-report-item.is-focused')?.getBoundingClientRect(),heading=document.querySelector('.my-reports-panel .history-heading')?.getBoundingClientRect();return card&&heading&&card.top>=heading.bottom+15})
   assert.equal(await shell.locator('.my-report-item.is-focused .my-report-summary').getAttribute('aria-expanded'),'true')
   await page.screenshot({path:path.join(output,`notification-report-target-${width}.png`)})
   await backToTop()
   assert.equal(await shell.getByRole('group',{name:'조회 기간'}).getByRole('button',{name:'전체',exact:true}).getAttribute('aria-pressed'),'true')
   assert.equal(await shell.locator('.my-report-item').count(),27)
   await stable()
   await nav.getByRole('button',{name:/^알림/}).click()
   await shell.getByRole('button',{name:/중간 제보 확인/}).click()
   await shell.locator('.my-report-item.is-focused .my-report-detail').waitFor()
   await page.waitForFunction(()=>{const card=document.querySelector('.my-report-item.is-focused')?.getBoundingClientRect(),heading=document.querySelector('.my-reports-panel .history-heading')?.getBoundingClientRect();return card&&heading&&Math.abs(card.top-heading.bottom-16)<=1})
   assert.match(await shell.locator('.my-report-item.is-focused .my-report-summary strong').innerText(),/목록 시험 15/)
   await stable();await page.screenshot({path:path.join(output,`notification-middle-report-${width}.png`)})
   // Create actual memory-only reviews through the UI, never inject review state.
   const reviewCount=width===390?13:1
   for(let i=0;i<reviewCount;i++) {
    await nav.getByRole('button',{name:'지도',exact:true}).click()
    // One review per toilet per rolling day, oldest first. The 30-day filter exercises pagination.
    await page.evaluate(time=>{window.historyTestNow=time},now-(reviewCount-1-i)*day)
    await page.locator('.map-stage .place-card').getByRole('button',{name:'리뷰',exact:true}).click()
    const form=page.getByRole('dialog',{name:'리뷰 쓰기',exact:true})
    await form.getByRole('radio',{name:'만족도 4점'}).check();await form.getByRole('radio',{name:'청결도 5점'}).check();await form.getByRole('button',{name:'있었어요',exact:true}).click();await form.locator('textarea').fill(`리뷰 목록 시험 ${String(reviewCount-i).padStart(2,'0')}`);await form.getByRole('button',{name:'리뷰 남기기',exact:true}).click();await page.getByRole('button',{name:'지도로 돌아가기',exact:true}).click()
   }
   await page.evaluate(time=>{window.historyTestNow=time},now)
   await nav.getByRole('button',{name:'내 페이지',exact:true}).click();await shell.getByRole('button',{name:'내 리뷰',exact:true}).click()
   await shell.locator('.history-card').first().waitFor()
   assert.equal(await shell.evaluate(el=>el.scrollTop),0,'new review history must not inherit the account scroll position')
   assert.equal(await page.getByRole('dialog').count(),0)
   assert.equal(await shell.locator('.history-card').count(),Math.min(7,reviewCount))
   if(reviewCount>10){await backToTop();await shell.getByRole('button',{name:'최근 30일',exact:true}).click()}
   assert.match(await shell.locator('.history-card').first().innerText(),/리뷰 목록 시험 01/)
   assert.match(await shell.locator('.rv-my-stars').first().innerText(),/★ 4\.5 \/ 5/)
   assert.doesNotMatch(await shell.locator('.history-review-summary').first().innerText(),/청결/)
   await stable();await page.screenshot({path:path.join(output,`reviews-history-${width}.png`)})
   if(width===390){
    await shell.evaluate(el=>{el.scrollTop=el.scrollHeight});await page.waitForFunction(()=>document.querySelectorAll('.mobile-page .history-card').length===13)
    const reviewsHeading=await shell.locator('.history-heading').boundingBox(), reviewsShell=await shell.boundingBox()
    assert.ok(Math.abs(reviewsHeading.y-reviewsShell.y)<=1,'review title and close stay pinned while scrolling')
    assert.equal(await shell.getByRole('button',{name:'내 리뷰 닫기'}).isVisible(),true)
    await backToTop()
    assert.equal(await shell.getByRole('button',{name:'최근 30일',exact:true}).getAttribute('aria-pressed'),'true','TOP preserves the selected review period')
    assert.equal(await shell.locator('.history-card').count(),13)
   }
   await shell.locator('.history-card').first().getByRole('button').click();await shell.locator('.rv-full-comment').waitFor();await stable()
   assert.equal(await shell.locator('.rv-full-review dl>div').filter({hasText:'만족도'}).locator('dd').innerText(),'★ 4 / 5')
   assert.equal(await shell.locator('.rv-full-review dl>div').filter({hasText:'청결도'}).locator('dd').innerText(),'★ 5 / 5')
   await page.screenshot({path:path.join(output,`reviews-expanded-${width}.png`)})
   const trash=shell.getByRole('button',{name:'작성자 정보 지우기',exact:true}), edit=shell.getByRole('button',{name:'수정하기',exact:true})
   const trashBox=await trash.boundingBox(), editBox=await edit.boundingBox()
   assert.ok(trashBox.x>=editBox.x+editBox.width && Math.abs(trashBox.y-editBox.y)<1,'trash sits to the right of edit on the same row')
   assert.equal(trashBox.width,40);assert.equal(trashBox.height,40);assert.equal(editBox.height,40,'review actions share the compact 40px height')
   assert.equal(await trash.innerText(),'');assert.equal(await trash.locator('svg').count(),1)
   await trash.click();await shell.locator('.history-remove-confirm').waitFor()
   assert.match(await shell.locator('.history-remove-confirm').innerText(),/이 리뷰의 작성자 이름만 ‘익명’/)
   assert.match(await shell.locator('.history-remove-confirm').innerText(),/작성한 글은 삭제되지 않아요/)
   assert.equal(await shell.locator('.history-card').count(),reviewCount,'opening confirmation never removes a review')
   await page.screenshot({path:path.join(output,`review-anonymous-confirm-${width}.png`)})
   await shell.getByRole('button',{name:'취소',exact:true}).click();await edit.waitFor()
   await shell.getByRole('button',{name:'수정하기',exact:true}).click();await page.getByRole('dialog',{name:'리뷰 수정'}).getByRole('radio',{name:'만족도 5점'}).check();await page.getByRole('dialog',{name:'리뷰 수정'}).locator('textarea').fill('수정 후에도 내 목록 안에 있어요');await page.getByRole('button',{name:'수정한 내용 저장'}).click();await page.getByRole('button',{name:'목록으로 돌아가기'}).click();await shell.getByText('수정 후에도 내 목록 안에 있어요',{exact:true}).first().waitFor();assert.equal(await page.getByRole('dialog').count(),0)
   assert.match(await shell.locator('.rv-my-stars').first().innerText(),/★ 5\.0 \/ 5/,'editing refreshes the average and retains the decimal for a perfect score')
   await backToTop()
   await shell.getByRole('button',{name:'날짜 직접 선택'}).click();await selectCalendarDate(shell,'시작일','2026-08-02');await selectCalendarDate(shell,'종료일','2026-08-02');await shell.getByRole('button',{name:'적용',exact:true}).click();await shell.getByText('이 기간에 남긴 리뷰가 없어요',{exact:true}).waitFor()
   await shell.getByRole('button',{name:'최근 7일',exact:true}).click();assert.equal(await shell.locator('.history-card').count(),Math.min(7,reviewCount))
   // Offline recovery and expiration clear private embedded contents.
   await shell.locator('.history-review-summary').first().click()
   await shell.getByRole('button',{name:'작성자 정보 지우기',exact:true}).click()
   await shell.getByRole('button',{name:'정보 지우기',exact:true}).click()
   assert.equal(await shell.locator('.history-card').count(),Math.min(6,reviewCount-1),'only the explicitly confirmed review leaves my list')
   assert.equal(await shell.getByText('수정 후에도 내 목록 안에 있어요',{exact:true}).count(),0)
   if(reviewCount>1)assert.match(await shell.locator('.history-card').first().innerText(),/리뷰 목록 시험 02/,'other reviews stay unchanged')
   await nav.getByRole('button',{name:'지도',exact:true}).click()
   const retainedRating=String(Number(((reviewCount*4+1)/reviewCount).toFixed(1)))
   await page.getByLabel(`체험 리뷰 평점: ${retainedRating}`,{exact:true}).waitFor()
   reportMode='offline';await showReports();await shell.getByRole('alert').filter({hasText:'인터넷'}).waitFor();reportMode='';await shell.getByRole('button',{name:'다시 불러오기'}).click();await shell.locator('.my-report-item').first().waitFor()
   reportMode='401';await showReports();await shell.getByRole('heading',{name:'로그인 · 간편가입',exact:true}).waitFor();assert.equal(await shell.locator('.my-report-item,.history-card').count(),0)
   await shell.getByRole('button',{name:'Google로 계속하기'}).click();await shell.locator('.my-report-item').first().waitFor()
   await backToTop()
   assert.equal(await shell.getByRole('button',{name:'최근 7일',exact:true}).getAttribute('aria-pressed'),'true')
   assert.equal(await page.getByRole('dialog').count(),0,'OAuth resumes embedded report history')
   reportMode='401';await showReports();await shell.getByRole('heading',{name:'로그인 · 간편가입',exact:true}).waitFor()
   nextOwner='another-history-owner';await shell.getByRole('button',{name:'Google로 계속하기'}).click();await shell.getByText('이 기간에 표시할 제보가 없어요',{exact:true}).waitFor()
   assert.equal(await shell.locator('.my-report-item,.history-card').count(),0,'previous owner records cleared')
   // Even an empty, short viewport must not gain list scroll space when filters grow.
   await page.setViewportSize({width,height:600})
   const emptyLayout=await shell.evaluate(el=>({top:el.scrollTop,height:el.scrollHeight}))
   await backToTop();await shell.getByRole('button',{name:'날짜 직접 선택'}).click()
   assert.deepEqual(await shell.evaluate(el=>({top:el.scrollTop,height:el.scrollHeight})),emptyLayout,'empty list scroll range stays unchanged with an open calendar')
   const filterBody=shell.locator('.history-date-popover'), filterBounds=await filterBody.boundingBox(), navBounds=await nav.boundingBox()
   assert.ok(filterBounds.y+filterBounds.height<=navBounds.y,'calendar stays above bottom navigation on short screens')
   await filterBody.evaluate(el=>{el.scrollTop=el.scrollHeight});await page.waitForTimeout(50)
   assert.equal(await shell.getByRole('button',{name:'날짜 직접 선택'}).getAttribute('aria-expanded'),'true','scrolling inside the calendar does not close it')
   assert.deepEqual(await shell.evaluate(el=>({top:el.scrollTop,height:el.scrollHeight})),emptyLayout,'calendar scroll stays separate from the list')
   await shell.getByRole('heading',{name:'내 제보',exact:true}).click();await page.waitForTimeout(250)
   assert.equal(await shell.getByRole('button',{name:'날짜 직접 선택'}).getAttribute('aria-expanded'),'false','outside interaction dismisses the calendar')
   assert.deepEqual(await shell.evaluate(el=>({top:el.scrollTop,height:el.scrollHeight})),emptyLayout)
   await shell.getByRole('button',{name:'내 제보 닫기'}).click();assert.equal(await page.locator('.history-scroll-top').count(),0,'no TOP on account home')
   await nav.getByRole('button',{name:/^알림/}).click();assert.equal(await page.locator('.history-scroll-top').count(),0,'no TOP added to notifications')
   await nav.getByRole('button',{name:'지도',exact:true}).click();assert.equal(await page.locator('.history-scroll-top').count(),0,'no TOP on map')
   assert.equal(await page.locator('.topbar').isVisible(),true,'returning to the map restores the logo and search header')
   assert.equal(writes,0);assert.deepEqual(errors,[])
   console.log(`PASS history ${width}: embedded reports/reviews, 7/30/all/custom, sorted, 10-item auto append, inline detail/edit return, offline retry, expiry, stable shell; reads=${reads}; no business writes`)
   await context.close()
  }
 } finally {await browser.close()}
})().catch(error=>{console.error(error);process.exitCode=1})
