import test from 'node:test'
import assert from 'node:assert/strict'
import {readFile} from 'node:fs/promises'
import { message } from '../src/i18n/messages.ts'

const source = async path => readFile(new URL(path, import.meta.url), 'utf8')

test('mobile search has no focus-dependent expansion and clears focus state on blur', async () => {
  const app = await source('../src/App.tsx')
  const css = await source('../src/components/mobile-navigation.css')
  assert.doesNotMatch(app + css, /is-mobile-searching|mobile-search-close/)
  assert.match(app, /onBlur=\{\(\) => setIsPlaceSearchFocused\(false\)\}/)
  assert.match(css, /place-search-input\s*\{[^}]*font-size: 16px/)
})

test('all mobile map sheets reserve the same upper control area', async () => {
  const css = await source('../src/components/mobile-navigation.css')
  assert.match(css, /\.has-mobile-navigation \.place-card, \.has-mobile-navigation \.coordinate-group-card, \.has-mobile-navigation \.mobile-area-list\s*\{ max-height: calc\(100% - 80px\); \}/)
  assert.match(css, /max-height: min\(280px, calc\(100% - 80px\)\)/)
})

test('coordinate group keeps its title visible while only the detail list scrolls', async () => {
  const app = await source('../src/App.tsx')
  const css = await source('../src/App.css')
  assert.match(app, /<header className="coordinate-group-header">[\s\S]*className="coordinate-group-description"/)
  assert.match(css, /\.coordinate-group-header\s*\{[^}]*flex: 0 0 auto/)
  assert.match(app, /list\.scrollTop \+ itemBounds\.top - listBounds\.top - 8/)
  assert.doesNotMatch(app, /item\.offsetTop - list\.offsetTop/)
  assert.match(app, /coordinate-group-admin-badge[^>]*>\{t\('map.admin'\)\}<svg[^>]*aria-hidden="true"/)
  assert.match(css, /\.coordinate-group-admin-badge\s*\{[^}]*font-size: 10px/)
  assert.match(app, /className="coordinate-group-meta-row"[\s\S]*className="coordinate-group-labels"[\s\S]*className="coordinate-group-distance"[\s\S]*coordinate-group-display-name/)
  assert.match(css, /\.coordinate-group-meta-row\s*\{[^}]*display: flex[^}]*justify-content: space-between[^}]*padding-right: 28px/)
  assert.doesNotMatch(css, /\.coordinate-group-distance\s*\{[^}]*position: absolute/)
})

test('report login prompt uses brand and concise labels without removing the auth gate', async () => {
  const app = await source('../src/App.tsx')
  const row = await source('../src/components/ToiletCommunityRow.tsx')
  assert.doesNotMatch(app, /로그인 후 정보 제보하기/)
  assert.match(row, /aria-label=\{t\('metric.reportHint'\)\} title=\{t\('metric.reportHint'\)\}/)
  assert.equal((app.match(/onReport=\{isDesktop \? undefined :/g) || []).length, 1)
  assert.match(app, /onReport=\{isDesktop && !REVIEW_UI_ENABLED \? undefined/)
  assert.match(app, /className="brand login-brand"[^>]*><BrandWordmark locale=\{locale\}/)
  assert.match(app, /const title = t\('auth.title'\)/)
})

test('English branding and mobile facility rows remain compact without overlapping location actions', async () => {
  const app = await source('../src/App.tsx')
  const mobile = await source('../src/components/MobileNavigation.tsx')
  const logo = await source('../src/components/BrandWordmark.tsx')
  const css = await source('../src/App.css')
  assert.match(app, /<BrandWordmark locale=\{locale\} \/>/)
  assert.match(mobile, /<BrandWordmark locale=\{locale\} \/>/)
  assert.match(logo, /<span>GEUP<\/span><span>DDONG<\/span>/)
  assert.match(css, /\.brand-wordmark\.is-english\s*\{[^}]*grid-template-rows: repeat\(2, auto\)/)
  assert.match(css, /\.brand-wordmark\.is-english > span\s*\{[^}]*font-size: \.72em/)
  assert.match(css, /\.facility-location-label\s*\{[^}]*grid-column: 1 \/ -1[^}]*justify-self: end/)
  assert.match(css, /\.coordinate-facility-location\s*\{[^}]*grid-column: 1 \/ -1[^}]*justify-self: end/)
})

test('login entry copy is one short purpose sentence and notifications use the shared title', async () => {
  const app = await source('../src/App.tsx')
  const mobile = await source('../src/components/MobileNavigation.tsx')
  assert.match(app, /review: 'review.loginRequired'/)
  assert.match(app, /'my-reports': 'auth.reportsLogin'/)
  assert.match(app, /report: 'auth.reportLogin'/)
  assert.doesNotMatch(app, /로그인한 뒤 리뷰 버튼을 다시 눌러 주세요\. 새 리뷰는/)
  assert.match(mobile, /<h1>\{t\('auth.title'\)\}<\/h1>/)
  assert.doesNotMatch(mobile, /로그인하고 알림을 확인하세요/)
  assert.match(app, /t\('auth.ageNote'\)/)
  assert.equal(message('ko', 'auth.title'), '로그인 · 간편가입')
  assert.equal(message('ko', 'review.loginRequired'), '리뷰는 로그인 후 이용할 수 있어요.')
  assert.equal(message('ko', 'auth.reportsLogin'), '내 제보는 로그인 후 확인할 수 있어요.')
  assert.equal(message('ko', 'auth.reportLogin'), '제보는 로그인 후 이용할 수 있어요.')
  assert.equal(message('ko', 'auth.ageNote'), '첫 가입 시 만 14세 이상 확인·필수 약관 동의가 필요해요.')
})

test('all login entry surfaces put Google before Kakao with matching provider handlers', async () => {
  for (const file of ['../src/App.tsx', '../src/components/MobileNavigation.tsx']) {
    const content = await source(file)
    const buttons = [...content.matchAll(/<button\b[^>]*className="social-login ([^"]+)"[^\r\n]+/g)].map(match => match[0])
    assert.equal(buttons.length, 2)
    assert.match(buttons[0], /google-login.*(?:startSocialLogin|onLogin)\('google'\)/)
    assert.match(buttons[1], /kakao-login.*(?:startSocialLogin|onLogin)\('kakao'\)/)
    assert.match(content, /auth.intro/)
    assert.equal(message('ko', 'auth.intro'), '구글·카카오로 간편하게 로그인하세요.')
    assert.doesNotMatch(content, /카카오·구글로/)
  }
})

test('community uses the shared three-second transient notice without navigating', async () => {
  const nav = await source('../src/components/MobileNavigation.tsx')
  const app = await source('../src/App.tsx')
  const hint = await source('../src/components/reviews/ReviewEntryHint.tsx')
  const preview = await source('../src/components/reviews/ReviewPreview.tsx')
  const detail = await source('../src/components/ToiletDetailContents.tsx')
  const css = await source('../src/components/mobile-navigation.css')
  const timing = await source('../src/lib/uiTiming.ts')
  assert.doesNotMatch(nav, /coming soon/)
  assert.match(nav, /onClick=\{showCommunityNotice\}/)
  assert.match(nav, /t\('nav.comingSoon'\)/)
  const { message } = await import('../src/i18n/messages.ts')
  assert.equal(message('ko', 'nav.comingSoon'), '준비 중이에요')
  assert.match(nav, /TRANSIENT_NOTICE_MS/)
  assert.match(timing, /TRANSIENT_NOTICE_MS = 3_000/)
  assert.match(nav, /clearTimeout\(noticeTimer.current\)/)
  assert.match(nav, /role="status" aria-live="polite"/)
  for (const transient of [nav, app, hint, preview, detail]) {
    assert.match(transient, /document\.addEventListener\('pointerdown',\s*dismiss/)
    assert.match(transient, /document\.addEventListener\('keydown',\s*dismiss/)
  }
  assert.doesNotMatch(css, /last-of-type\s*\{\s*height: 23px/)
})

test('compact navigation retains readable labels, touch targets and safe-area padding', async () => {
  const css = await source('../src/components/mobile-navigation.css')
  assert.match(css, /\.mobile-navigation button\s*\{[^}]*min-height: 52px/)
  assert.match(css, /max\(2px, env\(safe-area-inset-bottom\)\)/)
  assert.match(css, /\.mobile-navigation button\s*\{[^}]*font-size: 11px/)
})

test('future toilet metrics are placeholders in a 44px row, with a labeled report action', async () => {
  const app = await source('../src/components/ToiletCommunityRow.tsx')
  const css = await source('../src/components/mobile-navigation.css')
  for (const key of ['metric.rating', 'metric.crowding', 'metric.paper', 'metric.pending']) assert.ok(app.includes(key))
  assert.equal(message('ko', 'metric.pending'), '준비 중')
  assert.match(app, /<span>\{t\('metric.report'\)\}<\/span>/)
  assert.match(css, /\.toilet-community-row\s*\{[^}]*height: 44px/)
  assert.match(css, /\.toilet-community-row\s*\{[^}]*display: flex/)
  assert.match(css, /\.toilet-community-metric\s*\{[^}]*align-items: flex-start[^}]*text-align: left/)
  assert.match(css, /\.toilet-community-metric\s*\{[^}]*flex: 1 1 auto/)
  assert.match(css, /\.report-entry-button\.report-icon-button\s*\{[^}]*flex: 0 0 44px[^}]*margin: 0 0 0 12px/)
  assert.match(css, /\.toilet-community-row\s*\{[^}]*container-type: inline-size/)
  assert.match(css, /@container \(max-width: 240px\)[\s\S]*padding-right: 4px[\s\S]*padding-left: 4px[\s\S]*margin-left: 4px/)
  assert.match(css, /\.toilet-community-row\s*\{[^}]*background: transparent/)
  assert.match(css, /toilet-community-metric::before[^}]*width: 1px/)
  assert.match(css, /metric-star\s*\{ color: #b88524/)
  assert.match(app, /className="metric-paper"/)
  assert.match(app, /m13 12-4 1 1-4 7-7 3 3-7 7Z/)
})

test('group report action sits beside hours, apart from collapse; metrics and single-card behavior remain', async () => {
  const app = await source('../src/App.tsx')
  const inline = app.slice(app.indexOf('function CoordinateGroupInlineDetails'), app.indexOf('function CompactFacilityStatus'))
  assert.match(inline, /className="coordinate-opening-row"><p className="open-time">\{formatOpenTime\(toilet, locale\)\}<\/p>\{onReport && <ToiletReportEntry iconOnly onClick=\{onReport\} \/>\}<\/div>\s*<ToiletCommunityRow onReview=\{onReview\}/)
  assert.match(inline, /<ToiletReportEntry iconOnly disabled \/>/)
  assert.doesNotMatch(app, /review-group-title-row/)
  assert.equal((inline.match(/<ToiletCommunityRow/g) || []).length, 2)
  assert.equal((app.match(/onReport=\{isDesktop \? undefined :/g) || []).length, 1)
  assert.match(app, /onReport=\{isDesktop && !REVIEW_UI_ENABLED \? undefined/)
  const row = await source('../src/components/ToiletCommunityRow.tsx')
  assert.match(row, /size=\{iconOnly \? 20 : 18\}/)
  assert.match(row, /!iconOnly && <span>\{t\('metric.report'\)\}<\/span>/)
  assert.match(row, /: \(onReport \|\| pendingReport\) && <button disabled=\{pendingReport\}/)
  for (const key of ['metric.rating', 'metric.crowding', 'metric.paper', 'metric.pending']) assert.ok(row.includes(key))
  const css = await source('../src/components/mobile-navigation.css')
  assert.match(css, /\.toilet-community-row.is-readonly \.toilet-community-metric\s*\{ flex: 1 1 0/)
  assert.doesNotMatch(css, /\.toilet-community-row \+ \.open-time/)
})

test('review summaries follow the review action and divider, before addresses, while staying out of the collapsed mobile card', async () => {
  const app = await source('../src/App.tsx')
  const route = await source('../src/components/ToiletRouteBridge.tsx')
  const detail = await source('../src/components/ToiletDetailContents.tsx')
  const reviews = await source('../src/components/reviews/PublicReviews.tsx')
  const css = await source('../src/components/mobile-navigation.css')
  const single = app.slice(app.indexOf('<div ref={cardScrollRef} className="card-scroll-content">'), app.indexOf('{selectedCoordinateGroup && ('))
  const inline = app.slice(app.indexOf('function CoordinateGroupInlineDetails'), app.indexOf('function CompactFacilityStatus'))
  const routeScroll = route.slice(route.indexOf('<div className="card-scroll-content">'))
  for (const content of [single, inline, routeScroll]) {
    assert.ok(content.indexOf('<ToiletCommunityRow') >= 0)
    assert.ok(content.indexOf('<ToiletCommunityRow') < content.indexOf('<PublicReviews'))
  }
  assert.ok(single.indexOf('<PublicReviews') < single.indexOf('<ToiletDetailContents'))
  assert.ok(inline.indexOf('<PublicReviews') < inline.indexOf('className="coordinate-inline-address"'))
  assert.ok(routeScroll.indexOf('<PublicReviews') < routeScroll.indexOf('<ToiletDetailContents'))
  assert.doesNotMatch(detail, /PublicReviews/)
  assert.match(css, /\.public-reviews\s*\{[^}]*position: relative[^}]*width: 100%[^}]*margin-top: 22px/)
  assert.match(css, /\.public-review-summary-panel\s*\{[^}]*margin-top: 4px[^}]*padding: 12px 12px 16px[^}]*border: 1px solid #e2e9e4[^}]*border-radius: 14px/)
  assert.match(css, /\.public-reviews::before\s*\{[^}]*top: -12px[^}]*height: 1px[^}]*background: #e8ede9/)
  assert.match(css, /\.public-reviews \+ \.card-details\s*\{[^}]*margin-top: 12px[^}]*padding-top: 0[^}]*border-top: 0/)
  assert.match(css, /\.public-review-rating\s*\{[^}]*background: transparent/)
  assert.match(css, /\.public-review-summary-list\s*\{[^}]*gap: 14px[^}]*padding-top: 8px/)
  assert.doesNotMatch(css, /\.public-review-row\s*\{[^}]*border/)
  assert.match(css, /\.public-review-full-header\s*\{[^}]*padding: 50px 18px 8px/)
  assert.match(css, /\.public-review-full-title-row\s*\{[^}]*min-height: 44px/)
  assert.match(css, /\.public-review-full-header h2\s*\{[^}]*font-size: 19px[^}]*font-weight: 700/)
  assert.match(css, /\.public-review-back\s*\{[^}]*position: absolute[^}]*left: 6px[^}]*width: 32px[^}]*height: 32px/)
  assert.match(css, /\.public-review-back::before,[^}]*\.close-button::before\s*\{[^}]*inset: -6px/)
  assert.doesNotMatch(css, /\.public-review-full-header\s*\{[^}]*border-bottom/)
  assert.match(css, /\.public-review-full-reviews\s*\{[^}]*overflow-y: auto[^}]*overscroll-behavior: contain/)
  assert.match(css, /\.public-review-full-list\s*\{[^}]*padding: 12px 12px 16px[^}]*border: 1px solid #e2e9e4[^}]*border-radius: 14px/)
  assert.match(css, /\.place-card\.is-review-list-open > \.close-button\s*\{[^}]*top: 6px[^}]*right: 6px[^}]*width: 32px[^}]*height: 32px/)
  assert.match(reviews, /className="card-label public-review-full-type">\{toiletTypeLabel\(toiletType, locale\)\}/)
  assert.match(reviews, /className="review-card-title-row public-review-full-title-row"/)
  assert.match(reviews, /className="public-review-total-rating"/)
  assert.match(reviews, /t\('public.summary', \{ rating: fullRating, count: fullReviewCount \}\)/)
  assert.match(reviews, /<h3 id="public-review-full-list-title">\{t\('public.users'\)\}/)
  assert.ok(reviews.indexOf('<h3 id="public-review-full-list-title">') < reviews.indexOf('className="public-review-full-list"'))
  assert.match(css, /\.place-card:not\(\.mobile-card-expanded\) \.card-scroll-content > \.public-reviews,[\s\S]*display: none/)
  assert.match(reviews, /onClick=\{hasReviews \? handleSummaryClick : undefined\}/)
  assert.match(reviews, /<h2>\{t\('public.title'\)\} <span>\{fullReviewCount\}<\/span><\/h2>/)
  assert.match(reviews, /className="public-review-summary-panel"/)
  assert.match(reviews, /const comment = item\.comment\?\.trim\(\)/)
  assert.match(reviews, /\{comment && <p className="public-review-comment">\{comment\}<\/p>\}/)
  assert.doesNotMatch(reviews, /작성한 내용이 없어요/)
  assert.ok(reviews.indexOf('className="public-review-name"') < reviews.indexOf('className="public-review-rating"'))
  assert.match(css, /\.public-review-name\s*\{[^}]*flex: 0 1 auto/)
  assert.match(css, /\.public-review-meta time\s*\{[^}]*margin-left: auto/)
  assert.match(css, /\.public-review-comment\s*\{[^}]*margin: 6px 0 0 33px/)
})

test('single and group address rows keep label left and align value toward the right copy action without wrapping', async () => {
  const css = await source('../src/App.css')
  const mobile = await source('../src/components/mobile-navigation.css')
  assert.match(css, /\.detail-row.detail-address, \.detail-row.coordinate-inline-address\s*\{[^}]*grid-template-columns: auto minmax\(0, 1fr\)/)
  assert.match(css, /\.detail-row.detail-address > dt, \.detail-row.coordinate-inline-address > dt\s*\{[^}]*text-align: left/)
  assert.match(css, /\.detail-row.detail-address > dd, \.detail-row.coordinate-inline-address > dd\s*\{[^}]*grid-template-columns: minmax\(0, 1fr\) auto[^}]*max-width: none[^}]*text-align: right/)
  assert.match(css, /\.detail-row.detail-address > dd > span, \.detail-row.coordinate-inline-address > dd > span\s*\{[^}]*text-overflow: ellipsis[^}]*white-space: nowrap/)
  assert.match(css, /\.detail-row.detail-address \.copy-address-button, \.detail-row.coordinate-inline-address \.copy-address-button\s*\{[^}]*justify-self: end/)
  assert.match(mobile, /\.has-mobile-navigation \.mobile-card-expanded \.detail-address\s*\{ display: grid/)
  // Presentation truncation must never truncate what gets copied.
  const detail = await source('../src/components/ToiletDetailContents.tsx')
  assert.match(detail, /navigator.clipboard.writeText\(value\)/)
  assert.match(detail, /textarea.value = value/)
})
