import type { Locale } from '../../i18n/locale'

const copy = {
  ko: { nationalMap: '전국 지도', totalCount: '총 {count}개', allRegions: '전체 지역', regions: '지역별 지도', intro: '지도를 눌러 시·도를 고른 뒤 시·군·구의 화장실을 찾아보세요.', chooseProvince: '시·도 선택', chooseDistrict: '시·군·구 선택', toilets: '화장실', districts: '시·군·구', map: '지도', back: '전국 보기', nearby: '이 지역의 화장실', empty: '이 지역에서 표시할 화장실이 없습니다.', error: '화장실 목록을 불러오지 못했습니다.', open: '지도에서 보기', source: '행정 경계 자료', search: '주소 또는 장소 검색', account: '내 페이지', notifications: '알림', total: '전국 화장실', unavailable: '지도에서 위치 확인', explore: '지역 탐색', atlas: '선택 지도', provinceList: '시·도', districtList: '시·군·구', locationMap: '위치 지도', restroomList: '화장실 목록', outsideBoundary: '건은 경계 밖 좌표로 지역 집계에서 제외', loading: '지역 지도를 불러오는 중…', zoomDetails: '확대하면 작은 지역명과 개수가 보여요', mapError: '지도를 불러오지 못했습니다. 잠시 후 다시 시도해 주세요.', closeSelection: '선택 닫기', zoomIn: '지도 확대', zoomOut: '지도 축소', resetView: '전체 지도 맞춤' },
  en: { nationalMap: 'Korea map', totalCount: '{count} total', allRegions: 'All regions', regions: 'Explore regions', intro: 'Choose a province, then a district to see public restrooms.', chooseProvince: 'Choose a province', chooseDistrict: 'Choose a district', toilets: 'restrooms', districts: 'districts', map: 'Map', back: 'All regions', nearby: 'Restrooms in this district', empty: 'No visible restrooms in this district.', error: 'Could not load restrooms.', open: 'View on map', source: 'Boundary data', search: 'Search an address or place', account: 'My page', notifications: 'Notifications', total: 'Restrooms nationwide', unavailable: 'Check the location on the map', explore: 'Explore Korea', atlas: 'Interactive atlas', provinceList: 'Provinces', districtList: 'Districts', locationMap: 'Location map', restroomList: 'Restrooms', outsideBoundary: 'coordinates outside boundaries excluded from counts', loading: 'Loading the regional map…', zoomDetails: 'Zoom in for smaller regions and counts', mapError: 'Could not load the map. Please try again shortly.', closeSelection: 'Close selection', zoomIn: 'Zoom in', zoomOut: 'Zoom out', resetView: 'Fit whole map' },
  ja: { nationalMap: '全国地図', totalCount: '計{count}か所', allRegions: 'すべての地域', regions: '地域別マップ', intro: '都道府県に相当する地域を選び、市・郡・区のトイレを探せます。', chooseProvince: '広域地域を選択', chooseDistrict: '市・郡・区を選択', toilets: 'か所', districts: '地域', map: '地図', back: '全国を見る', nearby: 'この地域のトイレ', empty: '表示できるトイレがありません。', error: 'トイレ一覧を読み込めませんでした。', open: '地図で見る', source: '行政境界データ', search: '住所・場所を検索', account: 'マイページ', notifications: '通知', total: '全国のトイレ', unavailable: '地図で場所を確認', explore: '韓国の地域を探す', atlas: '地域選択マップ', provinceList: '広域地域', districtList: '市・郡・区', locationMap: '位置マップ', restroomList: 'トイレ一覧', outsideBoundary: '件は境界外の座標のため地域別集計から除外', loading: '地域マップを読み込み中…', zoomDetails: '拡大すると小さな地域名と件数を表示', mapError: '地図を読み込めませんでした。しばらくしてからお試しください。', closeSelection: '選択を閉じる', zoomIn: '拡大', zoomOut: '縮小', resetView: '全体を表示' },
  'zh-CN': { nationalMap: '全国地图', totalCount: '共{count}处', allRegions: '全部地区', regions: '按地区查找', intro: '选择广域地区，再选择市·郡·区查看公共厕所。', chooseProvince: '选择广域地区', chooseDistrict: '选择市·郡·区', toilets: '处厕所', districts: '个地区', map: '地图', back: '查看全国', nearby: '本地区的厕所', empty: '本地区没有可显示的厕所。', error: '无法加载厕所列表。', open: '在地图上查看', source: '行政边界数据', search: '搜索地址或地点', account: '我的页面', notifications: '通知', total: '全国厕所', unavailable: '在地图上查看位置', explore: '探索韩国各地区', atlas: '地区选择地图', provinceList: '广域地区', districtList: '市·郡·区', locationMap: '位置地图', restroomList: '厕所列表', outsideBoundary: '条坐标位于行政边界之外，未计入地区总数', loading: '正在加载地区地图…', zoomDetails: '放大查看较小地区名称及数量', mapError: '地图暂时无法加载，请稍后重试。', closeSelection: '关闭选择', zoomIn: '放大', zoomOut: '缩小', resetView: '显示完整地图' },
  'zh-TW': { nationalMap: '全國地圖', totalCount: '共{count}處', allRegions: '全部地區', regions: '依地區查找', intro: '選擇廣域地區，再選擇市·郡·區查看公共廁所。', chooseProvince: '選擇廣域地區', chooseDistrict: '選擇市·郡·區', toilets: '處廁所', districts: '個地區', map: '地圖', back: '查看全國', nearby: '本地區的廁所', empty: '本地區沒有可顯示的廁所。', error: '無法載入廁所清單。', open: '在地圖上查看', source: '行政邊界資料', search: '搜尋地址或地點', account: '我的頁面', notifications: '通知', total: '全國廁所', unavailable: '在地圖上查看位置', explore: '探索韓國各地區', atlas: '地區選擇地圖', provinceList: '廣域地區', districtList: '市·郡·區', locationMap: '位置地圖', restroomList: '廁所清單', outsideBoundary: '筆座標位於行政邊界之外，未計入地區總數', loading: '正在載入地區地圖…', zoomDetails: '放大查看較小地區名稱及數量', mapError: '地圖暫時無法載入，請稍後再試。', closeSelection: '關閉選擇', zoomIn: '放大', zoomOut: '縮小', resetView: '顯示完整地圖' },
  'zh-HK': { nationalMap: '全國地圖', totalCount: '共{count}個', allRegions: '全部地區', regions: '按地區尋找', intro: '選擇廣域地區，再選擇市·郡·區查看公廁。', chooseProvince: '選擇廣域地區', chooseDistrict: '選擇市·郡·區', toilets: '個公廁', districts: '個地區', map: '地圖', back: '查看全國', nearby: '本地區的公廁', empty: '本地區沒有可顯示的公廁。', error: '無法載入公廁清單。', open: '在地圖上查看', source: '行政邊界資料', search: '搜尋地址或地點', account: '我的頁面', notifications: '通知', total: '全國公廁', unavailable: '在地圖上查看位置', explore: '探索韓國各地區', atlas: '地區選擇地圖', provinceList: '廣域地區', districtList: '市·郡·區', locationMap: '位置地圖', restroomList: '公廁清單', outsideBoundary: '筆座標位於行政邊界之外，未計入地區總數', loading: '正在載入地區地圖…', zoomDetails: '放大查看較小地區名稱及數量', mapError: '地圖暫時無法載入，請稍後再試。', closeSelection: '關閉選擇', zoomIn: '放大', zoomOut: '縮小', resetView: '顯示完整地圖' },
} as const

export function regionText(locale: Locale) { return copy[locale] }
