import type { ReactNode } from 'react'
import { LocalizedPolicyFooter } from './LocalizedPolicyFooter'
import { accountPolicyPublication, policyPublicationAttributes } from '../lib/accountPolicyPublication'
import { reviewPolicyPublication, reviewPolicyPublicationAttributes } from '../lib/reviewPolicyPublication'
import { profilePhotoPolicyPublication, profilePhotoPolicyPublicationAttributes } from '../lib/profilePhotoPolicyPublication'
import { englishPolicyTitles, type EnglishPolicyKind } from '../i18n/policyTranslation'
import './policy-disclosure.css'
import { BrandWordmark } from './BrandWordmark'
const date = (value: string) => new Date(value).toLocaleString('en-GB', { timeZone: 'Asia/Seoul' })
const publicationNotice = accountPolicyPublication.status === 'draft' ? 'Draft revision for review · Effective date not set'
  : `Revised policy · Announced: ${date(accountPolicyPublication.announcedAt!)} · Effective: ${date(accountPolicyPublication.effectiveAt!)} (Korea time)`
const reviewNotice = reviewPolicyPublication.status === 'published' ? `Review policy · Announced and effective: ${date(reviewPolicyPublication.effectiveAt!)} (Korea time)` : 'Draft review policy · Effective date not set'
const photoNotice = profilePhotoPolicyPublication.status === 'published' ? `Profile photo policy · Announced and effective: ${date(profilePhotoPolicyPublication.effectiveAt!)} (Korea time)` : 'Draft profile photo policy · Effective date not set'

// A reading translation of PolicyPage.tsx. Original policy versions, dates and API consent keys stay unchanged.
function EnglishPolicyLayout({ kind, embedded, children }: { kind: EnglishPolicyKind; embedded?: boolean; children: ReactNode }) {
  const title = englishPolicyTitles[kind]
  if (embedded) return <section className="policy-combined-section">
    <header className="policy-combined-header"><h2>{title}</h2></header><div className="policy-combined-body">{children}</div>
  </section>
  return <main className="policy-page" lang="en">
    <header className="policy-header"><a href="/en" className="policy-brand" aria-label="Geupddong home"><BrandWordmark locale="en" /></a><a href="/en" className="policy-home-link">Back to map</a></header>
    <article className="policy-document" data-translation-status="preview" data-translation-source="ko"
      {...policyPublicationAttributes(accountPolicyPublication)} {...reviewPolicyPublicationAttributes(reviewPolicyPublication)} {...profilePhotoPolicyPublicationAttributes(profilePhotoPolicyPublication)}>
      <header className="policy-document-header">
        <p className="policy-eyebrow">Geupddong policies</p><h1>{title}</h1><p className="policy-effective">{publicationNotice}</p>
        <a className="policy-history-link" href="/policy-history/2026-09-01.html">Previous policy (Korean) <span>1 September 2026</span></a>
      </header>
      <aside className="policy-translation-note" aria-label="About this translation">
        <p>This English preview translation helps you read the Korean original. It does not change the agreement conditions, policy versions or effective dates.</p>
        <a href={`/policies/${kind}`} lang="ko">한국어 원문 보기</a>
      </aside>
      {accountPolicyPublication.status === 'published' && <section className="policy-change-notice" aria-label="Account policy changes">
        <h2>Changes to account closure and recovery</h2>
        <p>The revisions below apply from the effective time shown above. The previous policy applies before that time. Publication alone does not activate account features or count as consent to retain recovery data. The account screen explains whether each feature is available.</p>
        <ul><li>Recovery information is retained for 3 months only if you separately opt in when closing your account.</li><li>If you do not consent, request erasure or reach the end of the retention period, your account information becomes subject to erasure. Report and audit work records with personal information removed are retained.</li><li>The purpose and end-of-retention procedure for encrypted records kept in Korea to prevent deleted accounts from reappearing are explained below.</li></ul>
      </section>}
      {reviewPolicyPublication.status === 'published' && <section className="policy-change-notice" aria-label="Review policy changes">
        <h2>Review feature policy</h2><p>{reviewNotice}</p>
        <ul><li>Location, accuracy and measurement time are checked temporarily so that signed-in users can write reviews only when near the restroom.</li><li>Removing author information disconnects the author and changes the displayed name to “Anonymous”. Ratings and free-text comments remain as service information.</li><li>Review availability is controlled by separate server safety settings. Publishing this policy does not automatically activate reviews.</li></ul>
      </section>}
      {profilePhotoPolicyPublication.status === 'published' && <section className="policy-change-notice" aria-label="Profile photo policy changes">
        <h2>Profile photo storage policy</h2><p>{photoNotice}</p>
        <ul><li>Kakao photos optionally provided at sign-up, or photos uploaded by users, are converted to a small WebP image and stored in private Cloudflare R2 storage in the United States.</li><li>If you agree to provide your Kakao photo or upload a photo yourself, it is shown as your author photo on public reviews. You can turn this off at any time in My page.</li><li>Public photos may be temporarily cached on Cloudflare CDN for up to 5 minutes for faster display. When a photo is made private, replaced or deleted, public access is blocked and CDN cache deletion is requested.</li><li>You can use account features with the default avatar without providing a profile photo. Publishing this policy does not automatically activate the photo feature.</li></ul>
      </section>}
      {accountPolicyPublication.status === 'draft' && <p className="policy-draft-notice">This draft is not yet in effect. It will be finalized after checking how account information is stored, procedures for ending retention of personal-information copies and records that prevent deleted accounts from reappearing, and the announcement schedule. It does not replace the policy currently in effect.</p>}
      {children}
      <section className="policy-contact"><h2>Contact</h2><p>Operator: Geupddong (an individually operated service)</p><p>Privacy enquiries: <a href="mailto:privacy@geupddong.com">privacy@geupddong.com</a></p></section>
    </article><LocalizedPolicyFooter />
  </main>
}

export function EnglishPolicyPage({ kind, embedded = false }: { kind: EnglishPolicyKind; embedded?: boolean }) {
  const SectionHeading = embedded ? 'h3' : 'h2'
  if (kind === 'all') return <EnglishPolicyLayout kind={kind}>
    <nav className="policy-section-links" aria-label="Policy contents"><a href="#terms">Terms of Service</a><a href="#privacy">Privacy Policy</a><a href="#location">Location information</a></nav>
    <div id="terms"><EnglishPolicyPage kind="terms" embedded /></div><div id="privacy"><EnglishPolicyPage kind="privacy" embedded /></div><div id="location"><EnglishPolicyPage kind="location" embedded /></div>
  </EnglishPolicyLayout>
  if (kind === 'terms') return <EnglishPolicyLayout kind={kind} embedded={embedded}>
    <section><SectionHeading>1. Purpose</SectionHeading><p>These terms set out the conditions for using public restroom search, social login and information reporting provided by Geupddong, an individually operated service.</p></section>
    <section id="age"><SectionHeading>2. Confirmation of age 14 or older</SectionHeading><p>Geupddong account features are available only to people aged 14 or older. By continuing with sign-up, you confirm that you are at least 14. Children under 14 may browse the map and restroom information without logging in, but may not sign up, log in, submit reports or write reviews.</p></section>
    <section><SectionHeading>3. Accounts and social login</SectionHeading><p>Your account is activated after verification with Google or Kakao and agreement to the required terms. You must keep your account secure and must not use another person’s account. If you agree to provide your Kakao profile photo or upload one yourself, it is displayed as your author photo on public reviews. You can turn this off at any time in My page.</p></section>
    <section><SectionHeading>4. Reports, reviews and content</SectionHeading>
      <p>You must report factual information, such as restroom locations and opening hours, and write reviews based on your actual experience. Reports are approved or rejected after administrator review and may be edited or not applied to maintain service quality and safety.</p>
      <p>Do not include personal information, such as your own or another person’s real name, phone number or email address, in reviews. You may write one review per restroom every 24 hours, measured from the time of writing. You may edit a review or remove its author link yourself within 7 days of writing it. Removing the author link changes the name to “Anonymous” and removes the review from My reviews, but does not delete the rating, cleanliness score, toilet-paper availability, waiting time or written comment. You cannot subsequently edit it yourself or reconnect it to your account.</p>
      <p>Reviews involving infringement of rights, exposure of personal information or matters requiring action under applicable law may be separately edited or deleted. To request action concerning personal information, the author should provide the privacy contact with information identifying the review and the relevant part.</p>
    </section>
    <section><SectionHeading>5. Limitations of service information</SectionHeading><p>Information is based on public data and user reports. Actual availability, location and facility conditions may differ. In urgent situations, check on-site guidance and information from the relevant authorities first.</p></section>
    <section><SectionHeading>6. Restrictions and account closure</SectionHeading><p>Use may be restricted if service disruption, false reports or infringement of rights is confirmed. You may close your account from the account screen; service access and login sessions stop immediately. Only if you separately consent to 3 months of recovery retention can your account and report links be restored within that period, after verification with the same social account and explicit confirmation of recovery. Administrator permissions are not automatically restored. Without consent, or after the retention period expires, recovery is blocked and account information and member links in reports become subject to erasure. Pending requests are distinguished from completed erasure in the service database. Signing up after erasure creates a new account. Restroom information already applied from reports is retained.</p></section>
    <section><SectionHeading>7. Changes to these terms</SectionHeading><p>Important changes will be announced on the service before they take effect. We may ask you to agree again to revised required terms.</p></section>
  </EnglishPolicyLayout>

  if (kind === 'privacy') return <EnglishPolicyLayout kind={kind} embedded={embedded}>
    <section id="collection"><SectionHeading>1. Personal information collected</SectionHeading><ul>
      <li>Social login: provider, hash of the provider’s member identifier, display name, email address and email verification status.</li>
      <li>Profile photo: a converted image from a Kakao profile photo you agreed to provide at new sign-up, or a photo you uploaded; its visibility, collection source, and the version and time of the notice applied. Registered photos are shown as author photos on public reviews, and sharing can be turned off at any time in My page. Original files and original Kakao image URLs are not stored after conversion.</li>
      <li>Service use: roles, policies agreed to and their versions and timestamps, and last login time.</li>
      <li>Reports: target restroom, report content, selected coordinates and road-name address, processing status and administrator notes.</li>
      <li>Reviews: target restroom, satisfaction and cleanliness scores, toilet-paper availability, waiting time, optional comment, creation and modification times, author account link, and a review identifier used to prevent unauthorized changes.</li>
      <li>Review eligibility: current location, location accuracy and measurement time at the time of the request. The server checks that the location is within 150 m of the restroom, accuracy is 50 m or better, and the measurement is no more than 5 minutes old. Exact current-location coordinates are not saved in the review.</li>
      <li>Service usage statistics: page types; visits, views, sessions and engagement time; traffic sources; device, operating system and browser; country- and city-level connection area; search success and result-count ranges; and use of features such as markers, details, reports and reviews. Raw search terms, email addresses and account identifiers, precise locations and coordinates, restroom addresses and free-text input are not included in statistics collection requests.</li>
      <li>Operations and security: access records, audit logs and error records.</li>
    </ul></section>
    <section><SectionHeading>2. Purposes of use</SectionHeading><p>Information is used to identify members, provide social login, receive reports and provide processing results, verify review eligibility near the restroom, provide reviews and prevent misuse or duplicate use, respond to failures and improve service quality. Service usage statistics are used to aggregate usage volume and changes in major features, pages, traffic sources and device environments to identify failures and usability problems.</p></section>
    <section><SectionHeading>3. Retention periods</SectionHeading><ul>
      <li>Email address, verification status and ordinary login information: deleted or reset when the account is closed.</li>
      <li>Account recovery information: 3 calendar months from account closure, only if separately and optionally agreed to at closure. The social provider and protected unique identifier, nickname, account and report links, and consent, closure and scheduled erasure times are retained for recovery. Email addresses and social tokens are not retained for recovery.</li>
      <li>No consent to recovery retention, or an erasure request during retention: account and social identification information, per-member consents and notifications, and member links and free-text reasons in reports are erased. Signing up again with the same social login does not reconnect the previous account.</li>
      <li>Refresh tokens: up to 14 days after issuance, or until logout or account closure.</li>
      <li>Reviews: ratings, cleanliness scores, toilet-paper availability, waiting times and optional comments are retained while the service provides user experiences of the restroom. Selecting “Remove author information” removes the author account link and submission-request link and displays the author as “Anonymous”, but the review content remains. Editing or deletion is reviewed separately in cases such as reports of personal-information exposure or infringement of rights, legal obligations, or service closure.</li>
      <li>Location used for review eligibility: used only while processing the eligibility request and not stored in the review record.</li>
      <li>Reports and processing history: work records with personal information removed are retained without deletion merely because time has passed. When account information is erased, author links and free-text reasons and review notes that may contain personal information are removed. Approved information already applied to public restroom data is retained.</li>
      <li>Operational audit history: records of actions and processing results with personal information removed are retained without deletion merely because time has passed. This does not mean that originals containing personal information are kept permanently. When account information is erased, the identifying links and details for that member are removed.</li>
      <li>General access and system logs: this account-closure revision does not introduce a new service-wide time-based log deletion policy or storage method. Existing operational log rotation and capacity limits remain. Permanent storage of original logs is not guaranteed.</li>
    </ul><p>Consent to recovery retention is optional; you may close your account without it. During retention, you can sign in with the same social account and request immediate deletion without recovery, or contact the privacy email address. Information whose retention purpose has ended is destroyed using methods that make recovery difficult. Where applicable law requires separate retention, it is kept separately on the relevant basis and for the relevant period. If a failure delays erasure, retries occur while service use and recovery remain blocked.</p></section>
    <section><SectionHeading>4. External services</SectionHeading><p>We use Google and Kakao OAuth for login, Kakao Maps for maps and address verification, and Cloudflare for web delivery, security, email forwarding and profile photo storage. Each provider’s policies apply to information it processes during authentication and transmission. Service usage statistics are calculated directly on Geupddong servers rather than sent to a separate external analytics tool.</p></section>
    <section id="analytics"><SectionHeading>4-1. Service usage statistics</SectionHeading><p>To check service operation and usability problems, Geupddong servers aggregate page types, traffic-source categories, device environments and use of major features. Google analytics tags and Google Analytics cookies are not used.</p><dl className="policy-storage-facts">
      <div><dt>Purpose</dt><dd>Statistics on visits, views, traffic sources, device environments and major feature use, and service improvement.</dd></div>
      <div><dt>Traffic-source information</dt><dd>At the start of a session, only the previous website’s domain and the source and medium categories of share or campaign links issued by Geupddong are processed. Full previous-page URLs, search terms and query strings are not stored.</dd></div>
      <div><dt>Minimizing identification</dt><dd>Part of the connection-network information and device information are converted into period-specific cryptographic hashes to count repeat visits. Original IP addresses are not stored in the analytics tables.</dd></div>
      <div><dt>Browser storage</dt><dd>A random session value and initial traffic-source categories are kept in sessionStorage for the tab session. localStorage stores only whether a first visit has been recorded; this flag may remain until you clear the browser’s site data. Clearing site data resets session and first-visit counting but does not stop statistics collection.</dd></div>
      <div><dt>Retention</dt><dd>Individual analytics events are deleted after no more than 35 days. Daily aggregate statistics that do not contain personal information or original input text are retained to track long-term operating trends.</dd></div>
      <div><dt>Excluded data</dt><dd>Raw search terms, member and social identifiers, precise GPS and restroom coordinates and addresses, and free-text report and review content.</dd></div>
    </dl></section>
    <section id="profile-photo-overseas"><SectionHeading>4-2. Overseas profile photo storage and caching</SectionHeading><p>{photoNotice}</p><dl className="policy-storage-facts">
      <div><dt>Transferred items</dt><dd>Profile photos converted to WebP, at most 256×256 pixels.</dd></div>
      <div><dt>Country, timing and method</dt><dd>United States. Transferred online over encrypted communications when you consent to provide a Kakao photo at new sign-up or upload a photo yourself.</dd></div>
      <div><dt>Recipient</dt><dd>Cloudflare, Inc. · legal@cloudflare.com</dd></div>
      <div><dt>Purpose and period</dt><dd>Storage in private R2 to display the photo to you and provide it as your author photo on public reviews, until you delete the photo or close your account.</dd></div>
      <div><dt>Public display and caching</dt><dd>While sharing on reviews is enabled, the converted image is provided at a dedicated public URL and may be temporarily cached on Cloudflare CDN for up to 5 minutes for faster display. Browsers use ETags to recheck whether a photo has changed. Turning off sharing, replacing or deleting a photo, or closing your account blocks public access on the server and requests CDN cache deletion. Cache copies already delivered may remain visible temporarily until deletion is complete or the maximum 5-minute cache period expires.</dd></div>
      <div><dt>How to decline and the effects</dt><dd>You can decline to provide a photo on the Kakao sign-up screen or choose not to upload a profile photo. After registration, you can also turn off review photo sharing in My page. Account features remain available with the default avatar.</dd></div>
    </dl></section>
    <section id="erasure-records"><SectionHeading>4-3. Backups and records that prevent deleted accounts from reappearing</SectionHeading>
      <p>Erasing account information in the service database, optionally retaining recovery information for 3 months, encrypted backups, and records that prevent deleted accounts from reappearing are separate processes. An account-information erasure confirmation does not mean all existing copies were erased simultaneously.</p>
      <p>Recovery is blocked after the recovery deadline of 3 calendar months from account closure. Expired information becomes eligible for the regular erasure job after the daily public-data collection ends. Failures are managed as pending or failed, not marked as complete.</p>
      <p>Minimal records are kept separately and applied during restoration checks to prevent old accounts in backups from being restored. These records are not assumed to be anonymous merely because they are encrypted.</p>
      <dl className="policy-storage-facts">
        <div><dt>Location and operator</dt><dd>A separate file area on a server in Korea managed by the Geupddong operator. Access is restricted and kept separate from the service database.</dd></div>
        <div><dt>Storage structure</dt><dd>Per-member records that prevent deleted accounts from reappearing are configured to be stored as encrypted local files. New records of this kind are not stored in Cloudflare R2. Because they are separate files on the same server, they are not an independent backup protecting against loss of the entire server or disk.</dd></div>
        <div><dt>Recorded items</dt><dd>Minimal processing evidence, such as internal member ID, sign-up time, closure identifier, erasure-due time, database restore generation and format information, and erasure confirmation time. Email addresses, nicknames and social tokens are not included in this ledger.</dd></div>
        <div><dt>Timing and method</dt><dd>Before final account-information erasure, an encrypted protective record is saved to a local file, and evidence confirming the result is kept. Independent verification criteria are checked against separately retained verification records.</dd></div>
        <div><dt>Conditions for ending retention</dt><dd>We confirm that the member’s information has been erased from the service database and check whether old copies capable of restoring the member still exist. After confirming that related copies are gone, no restore is in progress, and independent verification criteria are updated, the member’s record is erased through a review and approval process. The current tool’s 32 days after the first confirmation of absence from the database is a minimum waiting threshold to begin review, not a statutory retention period or automatic deletion date. It is also separate from the 3-month recovery retention period.</dd></div>
      </dl>
      <p>Separately retained private independent-verification records contain aggregate counts, verification hashes and restore generations rather than member-by-member lists. They do not contain original per-member ledger records or encryption keys. Changing to local storage does not mean all processing by external services used for web delivery, authentication and independent verification is confined to Korea.</p>
      <p>Checks cover encrypted database backups, database change logs, old Redis persistence files, previous database volumes, temporary restore copies and remaining copies in previously used external storage. Missing evidence or failed checks are not treated as proof that no copies exist. Reasons for continued retention are reviewed, and personal-information records no longer needed become subject to erasure. You may request deletion or suspension of processing through the contact below.</p>
    </section>
    <section><SectionHeading>5. Your rights</SectionHeading><p>You may check the processing status of your reports and view My reviews. Within 7 days of writing a review, you may edit it yourself or remove its author link. You may close your account from the account screen. For reviews past the self-service period, or for requests to access, correct, delete or suspend processing of personal information in review text, email the contact with information identifying the review and the relevant part.</p></section>
    <section><SectionHeading>6. Security measures</SectionHeading><p>We use HttpOnly secure cookies, short-lived JWTs, Redis-based refresh-token revocation, separate storage for passwords and tokens, access controls and audit logs.</p></section>
    <section><SectionHeading>7. Children under 14</SectionHeading><p>Geupddong account features are not intended for children under 14. If a user is confirmed to be under 14, access to account features is stopped and the related account information is deleted.</p></section>
  </EnglishPolicyLayout>

  return <EnglishPolicyLayout kind={kind} embedded={embedded}>
    <section><SectionHeading>1. When is location used?</SectionHeading><p>When you press the current-location button, or when the browser requests location permission on your first visit, location is used to find nearby restrooms and calculate straight-line distances. When a signed-in user tries to write a review, a recent location is used again to check proximity to the restroom.</p></section>
    <section><SectionHeading>2. Is it stored on the server?</SectionHeading><p>Device GPS coordinates used for ordinary map browsing are not stored on Geupddong servers. They are used only in the browser to center the map and calculate distances. When writing a review, the current location, accuracy and measurement time are sent to the server to check that you are within 150 m of the target restroom, accuracy is 50 m or better, and the measurement is no more than 5 minutes old. Exact current-location coordinates are not saved in the review.</p></section>
    <section><SectionHeading>3. Exception: location reports</SectionHeading><p>If you submit a location report yourself, the coordinates and road-name address confirmed on the screen are stored to process your report. A final confirmation screen is provided before submission.</p></section>
    <section><SectionHeading>4. Refusing or withdrawing permission</SectionHeading><p>You can still search addresses and places and browse the map if you refuse location permission. You can change the permission at any time through the site settings in your browser’s address bar.</p></section>
  </EnglishPolicyLayout>
}
